/* Copyright 2007 - 2012 GOYAX.de */var goyax_params=new Object();function goyaxAddOnLoadEvent(obj,func)
{var oldonload=obj.onload;if(typeof obj.onload!='function'){obj.onload=func;}
else{obj.onload=function(){if(oldonload){oldonload();}func();}}}
function goyaxWidget(p)
{var widget=document.getElementById(p['id']);if(widget==null){alert("Der Code darf nur unveraendert eingebunden werden!");}
else{if(p['width']!=''&&p['width']>=2){var width=p['width']-2;widget.style.width=width+'px';}
if(p['height']!=''&&p['height']>=2){var height=p['height']-2;widget.style.height=height+'px';}
widget.style.visibility='hidden';goyaxAddOnLoadEvent(window,function(){goyaxRenderWidget(p);});}}
function goyaxRenderWidget(p)
{var goyax_host=p['host']||'tools.goyax.de';var id=p['id'];var wtype=p['wtype']||'';var version=p['version']||1;var style=p['style']||'';var apikey=p['api_key']||'';var isin=p['isin']||'';var chart=p['chart']||'';var span=p['span']||'';var width=p['width']||'';var height=p['height']||'';var target=p['target']||'';var widget=document.getElementById(id);if(widget!=null){var style_link=document.createElement('link');style_link.rel='stylesheet';style_link.href='http://'+goyax_host+'/style/widgets/widget_footer.css?wtype='+wtype+'&id='+id+'&version='+version+'&style='+style+'&chart='+chart+'&width='+width+'&height='+height;style_link.type='text/css';style_link.media='screen,projection';document.getElementsByTagName('head')[0].appendChild(style_link);var url='http://'+goyax_host+'/tools/widget?wtype='+wtype+'&version='+version+'&style='+style+'&chart='+chart+'&span='+span+'&width='+width+'&target='+target+'&apikey='+apikey+'&isin='+isin;var frame='';frame=document.createElement('iframe');frame.src=url;frame.marginWidth='0';frame.marginHeight='0';frame.vSpace='0';frame.hSpace='0';frame.allowTransparency='0';frame.frameBorder='0';frame.id=id+'_frame';widget.appendChild(frame);widget.insertBefore(frame,widget.firstChild);widget.style.visibility='visible';}}